### PR TITLE
Added micro-reddit solution

### PR DESCRIPTION
**Pull request by OmarMoataz**

### CODE REVIEW

**Comment by KevinMulhern** [comment]
Hey @OmarMoataz, looks like you've got an extra pare of `DS_store` files included in this PR. Can you remove them please? :)

**Comment by OmarMoataz** [comment]
I specifically removed them before committing. I can't find them because they're deleted.

**Comment by OmarMoataz** [comment]
It does say binary files removed.

**Comment by KevinMulhern** [comment]
Oops, sorry my mistake.

**Pull request merged**
